MAP_RESOLUTION = 100;
MAP_SIZE = 500

PIXEL_SIZE = MAP_SIZE / MAP_RESOLUTION;

ROBOT_SIZE = 8 * PIXEL_SIZE
SENSOR_SIZE = 4 * PIXEL_SIZE
SOURCE_RADIUS = 4 * PIXEL_SIZE

DEFAULT_INTENSITY = 100;

MOMENT_OF_INERTIA = 2

FPS = 60;